sudo: required
services:
  - docker

before_install:
  - docker build -t camario25/docker-react1 -f Dockerfile . 

script:
  - docker run -dit -e CI=true  camario25/docker-react1 npm run test

deploy:
  edge: true 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Mario"
  env: "Mario-env"
  bucket_name: "elasticbeanstalk-us-east-1-967195537723"
  bucket_path: "Mario"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key 
